FROM openjdk:latest

ADD ./target/authentication-service-0.0.1-SNAPSHOT.jar  authentication-service.jar
ADD authdb.mv.db authdb.mv.db
ADD authdb.trace.db authdb.trace.db
RUN sh -c 'touch /authentication-service.jar'
ENV JAVA_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n"
EXPOSE 9090
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar /authentication-service.jar" ]